"""Database create

Revision ID: c44276e0a9ac
Revises: 
Create Date: 2024-05-06 00:16:09.667778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44276e0a9ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute("CREATE SCHEMA ws")

    op.create_table('client',
    sa.Column('ID_CLIENT', sa.Integer(), nullable=False),
    sa.Column('AGE', sa.Integer(), nullable=False),
    sa.Column('GENDER', sa.String(), nullable=False),
    sa.Column('EDUCATION', sa.String(), nullable=False),
    sa.Column('MARITAL_STATUS', sa.String(), nullable=False),
    sa.Column('CHILD_TOTAL', sa.Integer(), nullable=False),
    sa.Column('DEPENDANTS', sa.Integer(), nullable=False),
    sa.Column('SOCSTATUS_WORK_FL', sa.Integer(), nullable=False),
    sa.Column('SOCSTATUS_PENS_FL', sa.Integer(), nullable=False),
    sa.Column('REG_ADDRESS_PROVINCE', sa.String(), nullable=False),
    sa.Column('FACT_ADDRESS_PROVINCE', sa.String(), nullable=False),
    sa.Column('POSTAL_ADDRESS_PROVINCE', sa.String(), nullable=False),
    sa.Column('FL_PRESENCE_FL', sa.Integer(), nullable=False),
    sa.Column('OWN_AUTO', sa.Integer(), nullable=False),
    sa.Column('PERSONAL_INCOME', sa.Integer(), nullable=False),
    sa.Column('Loan_count', sa.Integer(), nullable=False),
    sa.Column('CLOSED_FL', sa.Integer(), nullable=False),
    sa.Column('TARGET', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_CLIENT'),
    schema='ws'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client', schema='ws')
    # ### end Alembic commands ###
