"""Database create

Revision ID: fe440ca04e01
Revises: 
Create Date: 2024-05-08 12:59:53.899873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe440ca04e01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('ID_CLIENT', sa.Integer(), nullable=False),
    sa.Column('AGE', sa.Integer(), nullable=False),
    sa.Column('GENDER', sa.Integer(), nullable=False),
    sa.Column('EDUCATION', sa.String(), nullable=False),
    sa.Column('MARITAL_STATUS', sa.String(), nullable=False),
    sa.Column('CHILD_TOTAL', sa.Integer(), nullable=False),
    sa.Column('DEPENDANTS', sa.Integer(), nullable=False),
    sa.Column('SOCSTATUS_WORK_FL', sa.Integer(), nullable=False),
    sa.Column('SOCSTATUS_PENS_FL', sa.Integer(), nullable=False),
    sa.Column('REG_ADDRESS_PROVINCE', sa.String(), nullable=False),
    sa.Column('FACT_ADDRESS_PROVINCE', sa.String(), nullable=False),
    sa.Column('POSTAL_ADDRESS_PROVINCE', sa.String(), nullable=False),
    sa.Column('FL_PRESENCE_FL', sa.Integer(), nullable=False),
    sa.Column('OWN_AUTO', sa.Integer(), nullable=False),
    sa.Column('PERSONAL_INCOME', sa.Integer(), nullable=False),
    sa.Column('Loan_count', sa.Integer(), nullable=False),
    sa.Column('CLOSED_FL', sa.Integer(), nullable=False),
    sa.Column('TARGET', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_CLIENT'),
    schema='ws'
    )
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('ID_CLIENT', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('AGE', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('GENDER', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('EDUCATION', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('MARITAL_STATUS', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('CHILD_TOTAL', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('DEPENDANTS', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('SOCSTATUS_WORK_FL', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('SOCSTATUS_PENS_FL', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('REG_ADDRESS_PROVINCE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('FACT_ADDRESS_PROVINCE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('POSTAL_ADDRESS_PROVINCE', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('FL_PRESENCE_FL', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('OWN_AUTO', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PERSONAL_INCOME', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Loan_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('CLOSED_FL', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('TARGET', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('client', schema='ws')
    # ### end Alembic commands ###
